// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BookLibConnect.BooksDatabase;

namespace BookLibConnect.BooksDatabase.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20220219161122_DownloadQuality")]
    partial class DownloadQuality
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");
                });

            modelBuilder.Entity("BookCodec", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodecsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "CodecsId");

                    b.HasIndex("CodecsId");

                    b.ToTable("BookCodec");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("BookLadder", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaddersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "LaddersId");

                    b.HasIndex("LaddersId");

                    b.ToTable("BookLadder");
                });

            modelBuilder.Entity("BookNarrator", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NarratorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "NarratorsId");

                    b.HasIndex("NarratorsId");

                    b.ToTable("BookNarrator");
                });

            modelBuilder.Entity("LadderRung", b =>
                {
                    b.Property<int>("LaddersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RungsOrderIdx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RungsGenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LaddersId", "RungsOrderIdx", "RungsGenreId");

                    b.HasIndex("RungsOrderIdx", "RungsGenreId");

                    b.ToTable("LadderRung");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudibleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Asin")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AdultProduct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<float?>("AverageRating")
                        .HasColumnType("REAL");

                    b.Property<int?>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeliveryType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DownloadQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileCodec")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseIv")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchandisingSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublisherName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublisherSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RunTimeLengthSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuLite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Unabridged")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Asin")
                        .IsUnique();

                    b.HasIndex("PurchaseDate");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LengthMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartOffsetMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterInfoId");

                    b.HasIndex("ParentChapterId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.ChapterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandIntroDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandOutroDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsAccurate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuntimeLengthMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("ComponentId")
                        .IsUnique();

                    b.ToTable("ChapterInfos");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Codec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Codecs");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DownloadQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileCodec")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseIv")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunTimeLengthSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuLite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Asin")
                        .IsUnique();

                    b.HasIndex("BookId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Conversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AveTrackLengthMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ChapterMarkAdjusting")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConvFormat")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConvMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestDirectory")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mp4AAudio")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NamedChapters")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("PreferEmbChapMarks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReducedBitRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShortChapDurSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("VariableBitRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VeryShortChapDurSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("ComponentId")
                        .IsUnique();

                    b.ToTable("Conversions");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Ladder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ladders");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Narrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Asin")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Narrators");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.PseudoAsin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LatestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PseudoAsins");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Rung", b =>
                {
                    b.Property<int>("OrderIdx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderIdx", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("Rungs");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuLite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Asin")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.SeriesBook", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sequence")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeriesId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("SeriesBooks");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibConnect.BooksDatabase.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookCodec", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibConnect.BooksDatabase.Codec", null)
                        .WithMany()
                        .HasForeignKey("CodecsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibConnect.BooksDatabase.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLadder", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibConnect.BooksDatabase.Ladder", null)
                        .WithMany()
                        .HasForeignKey("LaddersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookNarrator", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibConnect.BooksDatabase.Narrator", null)
                        .WithMany()
                        .HasForeignKey("NarratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LadderRung", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Ladder", null)
                        .WithMany()
                        .HasForeignKey("LaddersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibConnect.BooksDatabase.Rung", null)
                        .WithMany()
                        .HasForeignKey("RungsOrderIdx", "RungsGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Chapter", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.ChapterInfo", "ChapterInfo")
                        .WithMany("Chapters")
                        .HasForeignKey("ChapterInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookLibConnect.BooksDatabase.Chapter", "ParentChapter")
                        .WithMany("Chapters")
                        .HasForeignKey("ParentChapterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChapterInfo");

                    b.Navigation("ParentChapter");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.ChapterInfo", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Book", "Book")
                        .WithOne("ChapterInfo")
                        .HasForeignKey("BookLibConnect.BooksDatabase.ChapterInfo", "BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookLibConnect.BooksDatabase.Component", "Component")
                        .WithOne("ChapterInfo")
                        .HasForeignKey("BookLibConnect.BooksDatabase.ChapterInfo", "ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Book");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Component", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Book", "Book")
                        .WithMany("Components")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Conversion", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Book", "Book")
                        .WithOne("Conversion")
                        .HasForeignKey("BookLibConnect.BooksDatabase.Conversion", "BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookLibConnect.BooksDatabase.Component", "Component")
                        .WithOne("Conversion")
                        .HasForeignKey("BookLibConnect.BooksDatabase.Conversion", "ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Book");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Rung", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.SeriesBook", b =>
                {
                    b.HasOne("BookLibConnect.BooksDatabase.Book", "Book")
                        .WithMany("Series")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibConnect.BooksDatabase.Series", "Series")
                        .WithMany("Books")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Book", b =>
                {
                    b.Navigation("ChapterInfo");

                    b.Navigation("Components");

                    b.Navigation("Conversion");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Chapter", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.ChapterInfo", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Component", b =>
                {
                    b.Navigation("ChapterInfo");

                    b.Navigation("Conversion");
                });

            modelBuilder.Entity("BookLibConnect.BooksDatabase.Series", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
